# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(max_length=6)),
                ('register_name', models.CharField(default=' ', max_length=50)),
                ('register_type', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Attendee',
            },
        ),
    ]
