# Generated by Django 2.1.1 on 2018-09-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(max_length=7)),
                ('register_name', models.CharField(default=' ', max_length=50)),
                ('register_type', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Attendee',
            },
        ),
    ]
