# Generated by Django 2.1.1 on 2018-09-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='register_id',
            field=models.CharField(max_length=6),
        ),
    ]
