# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='register_name',
            field=models.CharField(default='foo', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='register_id',
            field=models.CharField(max_length=6),
        ),
    ]
