# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuing', '0002_auto_20170806_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='register_name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
