# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuing', '0003_auto_20170806_1556'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendee',
            table='Attendee',
        ),
    ]
